---
title: "Collision Frequency Trends for Various Vehicle Types in the Greater Toronto Area"
subtitle: "INF2167 Project - Group 7"
author: 
  - Stella Gregorski
  - Yiyang Qin
format: 
  revealjs:
    slide-number: true
    pdf-separate-fragments: true
    theme: dracula
    smaller: true
editor: visual
date: today
date-format: long
bibliography: Presentation_References.bib
---

## Introduction

Why is traffic system important?

- Economic and social impacts
- Urban areas face increasing collision risks
- Data-driven analysis supports evidence-based planning

## Motivation

What temporal and spatial patterns exist in Toronto traffic collisions, and how do collision risks vary across different travel modes?

- Study on Wujiang, China [@cite-wujiang] discovered high-risk spot at the connection with a major city, which is associated with high traffic volumes, ongoing construction projects, and high proportion of large trucks.
- Scientists in Iran [@cite-forecast] conducted a time series analysis in Zanjan Province for predicting the future morality in traffic, and the models shows a descending trend in traffic morality, associated with stricter traffic enforcement and education as time passed.
- Investigation on Toronto collision patterns supports evidence-based transportation planning and resource allocation

## Data

- The Toronto Police Service maintains data on traffic collisions they are called to respond to
- This data includes attributes such as:
  - **Month, Weekday, and Hour** when the collision took place
  - **Neighbourhood** where the collision took place
  - Binaries for whether five different types of vehicle were involved in the collision
    - These include **Automobile, Passenger Vehicle (public transportation), Motorcycle, Bicycle, and Pedestrian**
- Data collected between 2020 and 2026 was sourced from [@cite-tpsdata]

## Methods

- This project used the R programming language [@cite-R] and the tidyverse library [@cite-tidyverse] to do reproducible data analysis.
- Two primary steps were used to determine spatial and temporal trends in Toronto traffic collisions:
  1.  Exploratory Data Analysis and Statistical Visualization
  2.  Linear Regression Statistical Modeling

## Findings

- Collisions for all vehicle types are most frequent in the afternoon (from 13:00 - 17:00)
- Collisions for motorized vehicles are more frequent in the winter, while bicycles and pedestrians are in more collisions during the summer
- While spatial and temporal trends can be observed visually, they are not particularly well-correlated
  - Residuals are centered around zero, but have observable patterns and a non-constant spread
  - Adding vehicle type to the model worsened the correlation

## Implications

- Rush hour and winter weather are primary indicators of collision frequency
- We can temporally and spatially model collision risk, similar to prior research
- Until we have more data on non-automobile collisions, trends in these types of accidents may remain less modelable

## Conclusion

Key Takeaways

= Traffic collisions in Toronto exhibit clear temporal and seasonal patterns, with risks varying by travel mode.
- Recent TPS data can effectively identify collision trends and high-risk periods.

Future Research
- Incorporate additional variables such as weather and land use to improve explanatory power.
- Explore more advanced spatial and spatiotemporal models to better capture collision hotspots.
- Extend the analysis with additional years of data to evaluate long-term trends and the impact of future transportation policies.

## References

::: {#refs}
:::
